unit UPRODUTOS;

interface

uses
  Classes;

type
  TPRODUTOS = class(TPersistent)
  private
    FID_PRODUTO: integer;
    FGTIN: String;
    FBARRAS: String;
    FBARRAS_CX: String;
    FPRODUTO: String;
    FDESCRICAO_COMPRA: String;
    FDESCRICAO_COMPLEMENTAR: String;
    FCODIGO_BALANCA: integer;
    FREFERENCIA: String;
    FESTOQUE: int64;
    FESTOQUE_ANT: int64;
    FVALOR_VENDA: int64;
    FVALOR_COMPRA: int64;
    FCUSTO: int64;
    FNCM: String;
    FCEST: String;
    FPESO_LIQUIDO: int64;
    FPESO_BRUTO: int64;
    FMARGEM: int64;
    FMARGEM_ATAC: int64;
    FCARACTERISTICA: String;
    FMVA: int64;
    FRED_BASE_ICMS: int64;
    FOBS: String;
    FFOTO: String;
    FSTATUS: String;
    FMINIMO: int64;
    FRETORNO: String;
    FCOMISSAO_VISTA: integer;
    FCOMISSAO_PRAZO: integer;
    FDESCONTO: integer;
    FMARCA: integer;
    FGRUPO: integer;
    FDT_CADASTRO: TDate;
    FUNIDADE_COMECIAL: String;
    FUNIDADE_COMPRA: String;
    FST: String;
    FORIGEM: integer;
    FICMS: int64;
    FCST_PISCOFINS_ENTRADA: integer;
    FCST_PISCOFINS_SAIDA: integer;
    FCST_IPI: integer;
    FALIQ_PIS_SAIDA: int64;
    FALIQ_PIS_ENTRADA: int64;
    FALIQ_COFINS_SAIDA: int64;
    FALIQ_COFINS_ENTRADA: int64;
    FALIQ_FCP: int64;
    FNATUREZA_RECEITA_PISCOFINS: integer;
    FIPI_PERC: int64;
    FIPI_TIPO: String;
    FCST: String;
    FIAT: String;
    FIPPT: String;
    FTAXA_ISSQN: int64;
    FCSOSN: integer;
    FECF_ICMS_ST: String;
    FDT_ULTIMO_MOVIMENTO: Tdatetime;
    FANP: String;
    FHASH_TRIPA: String;
    FSINCRONISMO: integer;
    FSERVICO: String;
    FVALOR_ATACADO: int64;
    FTIPO_CADASTRO: String;
    FCOMPOSICAO: String;
    FGRADE: String;
    FVENDER_TOTALIZADO: String;
    FCOMBUSTIVEL: String;
    FCFOP: integer;
    FAPLICACAO: String;
    FSECAO: String;
    FLOCALIZACAO: String;
    FQTDE_PROMOCIONAL: integer;
    FVALOR_PROMOCIONAL: int64;
    FSUBSTANCIA: String;
    FCONTROLADO: String;
    FTIPO_ITEM: integer;
    FPESADO_CHECKOUT: String;
    FVRC: int64;
    FSELO: int64;
    FVALIDADE: integer;
    FIPI_CLASS_ENQDR: String;
    FIPI_CNPJ_PROD: String;
    FIPI_COD_SELO: String;
    FIPI_QTDE_SELO: integer;
    FIPI_COD_ENQDR: String;
    FIPI_VALOR_PAUTA: int64;
    FESCALA_RELEVANCIA: String;
    FTIPO_FATOR: String;
    FFATOR: int64;
    FANP_GLP_TAXA: int64;
    FANP_GNN_TAXA: int64;
    FANP_GNI_TAXA: int64;
    FANP_GLP_PESO_LIQ: int64;
    FALINHADO_GTIN: String;
  published
    property ID_PRODUTO: integer read FID_PRODUTO write FID_PRODUTO;
    property GTIN: String read FGTIN write FGTIN;
    property BARRAS: String read FBARRAS write FBARRAS;
    property BARRAS_CX: String read FBARRAS_CX write FBARRAS_CX;
    property PRODUTO: String read FPRODUTO write FPRODUTO;
    property DESCRICAO_COMPRA: String read FDESCRICAO_COMPRA write FDESCRICAO_COMPRA;
    property DESCRICAO_COMPLEMENTAR: String read FDESCRICAO_COMPLEMENTAR write FDESCRICAO_COMPLEMENTAR;
    property CODIGO_BALANCA: integer read FCODIGO_BALANCA write FCODIGO_BALANCA;
    property REFERENCIA: String read FREFERENCIA write FREFERENCIA;
    property ESTOQUE: int64 read FESTOQUE write FESTOQUE;
    property ESTOQUE_ANT: int64 read FESTOQUE_ANT write FESTOQUE_ANT;
    property VALOR_VENDA: int64 read FVALOR_VENDA write FVALOR_VENDA;
    property VALOR_COMPRA: int64 read FVALOR_COMPRA write FVALOR_COMPRA;
    property CUSTO: int64 read FCUSTO write FCUSTO;
    property NCM: String read FNCM write FNCM;
    property CEST: String read FCEST write FCEST;
    property PESO_LIQUIDO: int64 read FPESO_LIQUIDO write FPESO_LIQUIDO;
    property PESO_BRUTO: int64 read FPESO_BRUTO write FPESO_BRUTO;
    property MARGEM: int64 read FMARGEM write FMARGEM;
    property MARGEM_ATAC: int64 read FMARGEM_ATAC write FMARGEM_ATAC;
    property CARACTERISTICA: String read FCARACTERISTICA write FCARACTERISTICA;
    property MVA: int64 read FMVA write FMVA;
    property RED_BASE_ICMS: int64 read FRED_BASE_ICMS write FRED_BASE_ICMS;
    property OBS: String read FOBS write FOBS;
    property FOTO: String read FFOTO write FFOTO;
    property STATUS: String read FSTATUS write FSTATUS;
    property MINIMO: int64 read FMINIMO write FMINIMO;
    property RETORNO: String read FRETORNO write FRETORNO;
    property COMISSAO_VISTA: integer read FCOMISSAO_VISTA write FCOMISSAO_VISTA;
    property COMISSAO_PRAZO: integer read FCOMISSAO_PRAZO write FCOMISSAO_PRAZO;
    property DESCONTO: integer read FDESCONTO write FDESCONTO;
    property MARCA: integer read FMARCA write FMARCA;
    property GRUPO: integer read FGRUPO write FGRUPO;
    property DT_CADASTRO: TDate read FDT_CADASTRO write FDT_CADASTRO;
    property UNIDADE_COMECIAL: String read FUNIDADE_COMECIAL write FUNIDADE_COMECIAL;
    property UNIDADE_COMPRA: String read FUNIDADE_COMPRA write FUNIDADE_COMPRA;
    property ST: String read FST write FST;
    property ORIGEM: integer read FORIGEM write FORIGEM;
    property ICMS: int64 read FICMS write FICMS;
    property CST_PISCOFINS_ENTRADA: integer read FCST_PISCOFINS_ENTRADA write FCST_PISCOFINS_ENTRADA;
    property CST_PISCOFINS_SAIDA: integer read FCST_PISCOFINS_SAIDA write FCST_PISCOFINS_SAIDA;
    property CST_IPI: integer read FCST_IPI write FCST_IPI;
    property ALIQ_PIS_SAIDA: int64 read FALIQ_PIS_SAIDA write FALIQ_PIS_SAIDA;
    property ALIQ_PIS_ENTRADA: int64 read FALIQ_PIS_ENTRADA write FALIQ_PIS_ENTRADA;
    property ALIQ_COFINS_SAIDA: int64 read FALIQ_COFINS_SAIDA write FALIQ_COFINS_SAIDA;
    property ALIQ_COFINS_ENTRADA: int64 read FALIQ_COFINS_ENTRADA write FALIQ_COFINS_ENTRADA;
    property ALIQ_FCP: int64 read FALIQ_FCP write FALIQ_FCP;
    property NATUREZA_RECEITA_PISCOFINS: integer read FNATUREZA_RECEITA_PISCOFINS write FNATUREZA_RECEITA_PISCOFINS;
    property IPI_PERC: int64 read FIPI_PERC write FIPI_PERC;
    property IPI_TIPO: String read FIPI_TIPO write FIPI_TIPO;
    property CST: String read FCST write FCST;
    property IAT: String read FIAT write FIAT;
    property IPPT: String read FIPPT write FIPPT;
    property TAXA_ISSQN: int64 read FTAXA_ISSQN write FTAXA_ISSQN;
    property CSOSN: integer read FCSOSN write FCSOSN;
    property ECF_ICMS_ST: String read FECF_ICMS_ST write FECF_ICMS_ST;
    property DT_ULTIMO_MOVIMENTO: Tdatetime read FDT_ULTIMO_MOVIMENTO write FDT_ULTIMO_MOVIMENTO;
    property ANP: String read FANP write FANP;
    property HASH_TRIPA: String read FHASH_TRIPA write FHASH_TRIPA;
    property SINCRONISMO: integer read FSINCRONISMO write FSINCRONISMO;
    property SERVICO: String read FSERVICO write FSERVICO;
    property VALOR_ATACADO: int64 read FVALOR_ATACADO write FVALOR_ATACADO;
    property TIPO_CADASTRO: String read FTIPO_CADASTRO write FTIPO_CADASTRO;
    property COMPOSICAO: String read FCOMPOSICAO write FCOMPOSICAO;
    property GRADE: String read FGRADE write FGRADE;
    property VENDER_TOTALIZADO: String read FVENDER_TOTALIZADO write FVENDER_TOTALIZADO;
    property COMBUSTIVEL: String read FCOMBUSTIVEL write FCOMBUSTIVEL;
    property CFOP: integer read FCFOP write FCFOP;
    property APLICACAO: String read FAPLICACAO write FAPLICACAO;
    property SECAO: String read FSECAO write FSECAO;
    property LOCALIZACAO: String read FLOCALIZACAO write FLOCALIZACAO;
    property QTDE_PROMOCIONAL: integer read FQTDE_PROMOCIONAL write FQTDE_PROMOCIONAL;
    property VALOR_PROMOCIONAL: int64 read FVALOR_PROMOCIONAL write FVALOR_PROMOCIONAL;
    property SUBSTANCIA: String read FSUBSTANCIA write FSUBSTANCIA;
    property CONTROLADO: String read FCONTROLADO write FCONTROLADO;
    property TIPO_ITEM: integer read FTIPO_ITEM write FTIPO_ITEM;
    property PESADO_CHECKOUT: String read FPESADO_CHECKOUT write FPESADO_CHECKOUT;
    property VRC: int64 read FVRC write FVRC;
    property SELO: int64 read FSELO write FSELO;
    property VALIDADE: integer read FVALIDADE write FVALIDADE;
    property IPI_CLASS_ENQDR: String read FIPI_CLASS_ENQDR write FIPI_CLASS_ENQDR;
    property IPI_CNPJ_PROD: String read FIPI_CNPJ_PROD write FIPI_CNPJ_PROD;
    property IPI_COD_SELO: String read FIPI_COD_SELO write FIPI_COD_SELO;
    property IPI_QTDE_SELO: integer read FIPI_QTDE_SELO write FIPI_QTDE_SELO;
    property IPI_COD_ENQDR: String read FIPI_COD_ENQDR write FIPI_COD_ENQDR;
    property IPI_VALOR_PAUTA: int64 read FIPI_VALOR_PAUTA write FIPI_VALOR_PAUTA;
    property ESCALA_RELEVANCIA: String read FESCALA_RELEVANCIA write FESCALA_RELEVANCIA;
    property TIPO_FATOR: String read FTIPO_FATOR write FTIPO_FATOR;
    property FATOR: int64 read FFATOR write FFATOR;
    property ANP_GLP_TAXA: int64 read FANP_GLP_TAXA write FANP_GLP_TAXA;
    property ANP_GNN_TAXA: int64 read FANP_GNN_TAXA write FANP_GNN_TAXA;
    property ANP_GNI_TAXA: int64 read FANP_GNI_TAXA write FANP_GNI_TAXA;
    property ANP_GLP_PESO_LIQ: int64 read FANP_GLP_PESO_LIQ write FANP_GLP_PESO_LIQ;
    property ALINHADO_GTIN: String read FALINHADO_GTIN write FALINHADO_GTIN;
   function NomeTabela():string;
  end;

implementation

{TPRODUTOS}

function TPRODUTOS.NomeTabela: string;
begin
   Result:= 'PRODUTOS';
end;

end.